import Head from 'next/head'
import { Inter } from 'next/font/google'

import styles from '@/styles/Home.module.css'
import { Map } from "../components/Map";

const inter = Inter({
  variable: '--inter-font',
  subsets: ['latin']
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.variable}>
        <main className={styles.main}>
          <Map />
          <div>

            <div className="fixed top-0 left-0 h-full w-64 bg-white rounded-r-lg shadow-lg">
              <div className="px-4 py-2 bg-gray-100 rounded-t-lg">
                <h2 className="text-lg font-bold">Sidebar Title</h2>
              </div>
              <ul className="p-4">
                <li className="mb-2"><a href="#" className="text-gray-700 hover:text-gray-900">Item 1</a></li>
                <li className="mb-2"><a href="#" className="text-gray-700 hover:text-gray-900">Item 2</a></li>
                <li className="mb-2"><a href="#" className="text-gray-700 hover:text-gray-900">Item 3</a></li>
              </ul>
            </div>

          </div>
        </main>
      </div>
    </>
  )
}
